// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID         int64
	OwnerID    string
	Provider   string
	TokenType  string
	Ciphertext []byte
	TokenNonce []byte
	WrappedDek []byte
	DekNonce   []byte
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type RepoConfig struct {
	ID             string
	OwnerID        string
	Provider       string
	RepoOwner      string
	RepoName       string
	RepoFullName   string
	RepoCloneUrl   string
	DockerfilePath string
	WebhookSecret  string
	WebhookID      pgtype.Int8
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
