// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mutations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
  owner_id, provider, token_type, ciphertext, token_nonce, wrapped_dek, dek_nonce, expires_at 
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, owner_id, provider, token_type, ciphertext, token_nonce, wrapped_dek, dek_nonce, created_at, last_used_at, expires_at
`

type CreateCredentialParams struct {
	OwnerID    string
	Provider   string
	TokenType  string
	Ciphertext []byte
	TokenNonce []byte
	WrappedDek []byte
	DekNonce   []byte
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.OwnerID,
		arg.Provider,
		arg.TokenType,
		arg.Ciphertext,
		arg.TokenNonce,
		arg.WrappedDek,
		arg.DekNonce,
		arg.ExpiresAt,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Provider,
		&i.TokenType,
		&i.Ciphertext,
		&i.TokenNonce,
		&i.WrappedDek,
		&i.DekNonce,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, email, password_hash
) VALUES (
  $1, $2, $3
)
RETURNING id, email, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
