// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const getCredentialByOwnerIDAndTokenType = `-- name: GetCredentialByOwnerIDAndTokenType :one
SELECT id, owner_id, provider, token_type, ciphertext, token_nonce, wrapped_dek, dek_nonce, created_at, last_used_at FROM credentials
WHERE owner_id = $1 AND token_type = $2 LIMIT 1
`

type GetCredentialByOwnerIDAndTokenTypeParams struct {
	OwnerID   string
	TokenType string
}

func (q *Queries) GetCredentialByOwnerIDAndTokenType(ctx context.Context, arg GetCredentialByOwnerIDAndTokenTypeParams) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByOwnerIDAndTokenType, arg.OwnerID, arg.TokenType)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Provider,
		&i.TokenType,
		&i.Ciphertext,
		&i.TokenNonce,
		&i.WrappedDek,
		&i.DekNonce,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
